export const enteredInputValue = [
  '',
  ' ',
  'Avarage',
  50,
  'Space middle',
  '<htmlTag>',
  '中文',
  'Space at the end ',
  ' Space at the beg',
  'a',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  'dfjwGGe82H43g3uRiy53h',
];

export const checksFound = [
  'Empty value',
  'Space',
  'Average value',
  'Other chars then alphabetic',
  'Space in the middle',
  'You used html tags',
  'Non ASCII',
  'Space values at the end',
  'Space values at the beginning',
  'Minimum value',
  'Maximum values',
  'More than maximum values',
  'You looked at the page source',
];
